[database]
host = "replace-host"
port = "replace-port"
user = "replace-user"
pass = "replace-pass"

[express]
port = 8888

[firebase]
# If you are using an self hosted system, please read the following documentation on how to retrive the Service
# Account to get the notifications working (https://firebase.google.com/docs/admin/setup#initialize-sdk)
credentialLocation = ""
